# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-07-26 22:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='getlatlong',
            field=models.CharField(default=1, max_length=1000),
            preserve_default=False,
        ),
    ]
