# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-07-25 18:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Friend',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=60)),
                ('last_name', models.CharField(max_length=60)),
                ('email', models.CharField(max_length=60)),
                ('of_user', models.ManyToManyField(related_name='friends', to='login_app.User')),
            ],
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place_name', models.CharField(max_length=60)),
                ('street', models.CharField(max_length=60)),
                ('city', models.CharField(max_length=60)),
                ('state', models.CharField(max_length=2)),
                ('zip_code', models.IntegerField()),
                ('fit_type', models.CharField(max_length=60)),
                ('desc', models.TextField(max_length=60)),
                ('is_going', models.ManyToManyField(related_name='this_place', to='login_app.User')),
            ],
        ),
    ]
