# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-07-26 16:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_app', '0002_place_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='friend_going',
            field=models.ManyToManyField(related_name='that_place', to='login_app.Friend'),
        ),
        migrations.AlterField(
            model_name='place',
            name='date',
            field=models.DateField(),
        ),
    ]
