# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-07-26 23:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_app', '0002_place_getlatlong'),
    ]

    operations = [
        migrations.RenameField(
            model_name='place',
            old_name='getlatlong',
            new_name='getlat',
        ),
        migrations.AddField(
            model_name='place',
            name='getlong',
            field=models.CharField(default=1, max_length=1000),
            preserve_default=False,
        ),
    ]
